# Generated by Django 4.2.1 on 2023-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_category_title_en_category_title_pt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-title',), 'verbose_name_plural': 'Category/Industry'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_pt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
