# Generated by Django 4.2.1 on 2023-08-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0041_remove_userprofile_vendor_expiry_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state']},
        ),
    ]
